config/routes.rb
Rails.application.routes.draw do
  namespace :vendors do
    resources :pizzas, except: [ :index, :show ]
    resources :inventories, except: [ :index, :show ]
    get "home", to: "home#index", as: "home"
  end

  namespace :customers do
    resources :orders, only: [ :new, :create, :show ] do
      resources :order_sides, only: [ :new, :create ]
    end
    get "home", to: "home#index", as: "home"
  end

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  root "home#index"
end

app/controllers/customers/home_controller.rb
class Customers::HomeController < ApplicationController
  before_action :require_user

  def index
    @pizzas = Pizza.includes(:pizza_sizes).all
    @toppings = Inventory.where(item_type: "topping")
    @sides = Inventory.where(item_type: "side")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
      if current_role == "vendor"
        redirect_to vendors_home_path
      else
        redirect_to customers_home_path
      end
    end
  end
end

app/controllers/vendors/home_controller.rb
class Vendors::HomeController < ApplicationController
  before_action :require_user
  before_action :require_vendor

  def index
    @orders = Order.includes(:customer, order_pizzas: [ :pizza, :order_pizza_toppings ], order_sides: [ :inventory ]).all
    @pizzas = Pizza.all
    @inventories = Inventory.all
  end
end

app/controllers/vendors/inventories_controller.rb
class Vendors::InventoriesController < ApplicationController
  before_action :require_vendor
  before_action :set_inventory, only: [ :edit, :update, :destroy ]

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)
    if @inventory.save
      flash[:notice] = "Inventory is successfully created."
      redirect_to vendors_home_path
    else
      render :new
    end
  end

  def edit
    @inventory = Inventory.find(params[:id])
  end

  def update
    @inventory = Inventory.find(params[:id])
    if @inventory.update(inventory_params)
      flash[:notice] = "Inventory is successfully updated."
      redirect_to vendors_home_path
    else
      render :edit
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy
    flash[:notice] = "Inventory is successfully deleted."
    redirect_to vendors_home_path
  end

  private

  def set_inventory
    @inventory = Inventory.find_by(id: params[:id])
    unless @inventory
      flash[:alert] = "Inventory not found."
      redirect_to vendors_home_path
    end
  end

  def inventory_params
    params.require(:inventory).permit(:name, :category, :item_type, :price_per_piece, :quantity)
  end
end

app/controllers/vendors/pizzas_controller.rb
class Vendors::PizzasController < ApplicationController
  before_action :require_vendor
  before_action :set_pizza, only: [ :edit, :update, :destroy ]

  def new
    @pizza = Pizza.new
    @pizza.pizza_sizes.build
  end

  def create
    @pizza = Pizza.new(pizza_params)
    if @pizza.save
      flash[:notice] = "Pizza is successfully created. You can add suitable inventory for it."
      redirect_to vendors_home_path
    else
      render :new
    end
  end

  def update
    if @pizza.update(pizza_params)
      flash[:notice] = "Pizza \"#{@pizza.name}\" is successfully updated."
      redirect_to vendors_home_path
    else
      render :edit
    end
  end

  def destroy
    @pizza.destroy
    flash[:notice] = "Pizza is successfully deleted."
    redirect_to vendors_home_path
  end

  private

  def set_pizza
    @pizza = Pizza.find_by(id: params[:id])
    unless @pizza
      flash[:alert] = "Pizza not found."
      redirect_to vendors_home_path
    end
  end

  def pizza_params
    params.require(:pizza).permit(:name, :is_vegetarian, pizza_sizes_attributes: [ :id, :size, :price, :_destroy ])
  end
end

app/views/vendors/home/index.html.erb
<div class="container mx-auto p-4">
  <h1 class="text-3xl font-bold text-black mb-4">Vendor Dashboard</h1>
  <p class="text-lg text-black mb-4">Welcome, Vendor!</p>

  <div class="flex space-x-4 mb-4">
    <%= link_to 'New Pizza', new_vendors_pizza_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded' %>
    <%= link_to 'New Inventory', new_vendors_inventory_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded' %>
  </div>

  <h2 class="text-2xl font-bold text-black mb-4">Your Pizzas</h2>
  <table class="min-w-full bg-white mb-8">
    <thead>
      <tr>
        <th class="py-2 px-4 bg-blue-500 text-white">Name</th>
        <th class="py-2 px-4 bg-blue-500 text-white">Vegetarian</th>
        <th class="py-2 px-4 bg-blue-500 text-white">Sizes</th>
        <th class="py-2 px-4 bg-blue-500 text-white"></th>
      </tr>
    </thead>
    <tbody>
      <% @pizzas.each do |pizza| %>
        <tr>
          <td class="py-2 px-4 border-b border-gray-200"><%= pizza.name %></td>
          <td class="py-2 px-4 border-b border-gray-200"><%= pizza.is_vegetarian ? 'Yes' : 'No' %></td>
          <td class="py-2 px-4 border-b border-gray-200">
            <% pizza.pizza_sizes.each do |size| %>
              <p>Size: <%= size.size %>, Price: <%= size.price %></p>
            <% end %>
          </td>
          <td class="py-2 px-4 border-b border-gray-200">
            <div class="flex space-x-2">
              <%= link_to 'Edit', edit_vendors_pizza_path(pizza), class: 'bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded' %>
              <%= button_to 'Delete', vendors_pizza_path(pizza), method: :delete, data: { confirm: 'Are you sure?' }, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2 class="text-2xl font-bold text-black mb-4">Your Inventories</h2>
  <table class="min-w-full bg-white mb-8">
    <thead>
      <tr>
        <th class="py-2 px-4 bg-blue-500 text-white">Name</th>
        <th class="py-2 px-4 bg-blue-500 text-white">Category</th>
        <th class="py-2 px-4 bg-blue-500 text-white">Item Type</th>
        <th class="py-2 px-4 bg-blue-500 text-white">Price Per Piece</th>
        <th class="py-2 px-4 bg-blue-500 text-white">Quantity</th>
        <th class="py-2 px-4 bg-blue-500 text-white"></th>
      </tr>
    </thead>
    <tbody>
      <% @inventories.each do |inventory| %>
        <tr>
          <td class="py-2 px-4 border-b border-gray-200"><%= inventory.name %></td>
          <td class="py-2 px-4 border-b border-gray-200"><%= inventory.category %></td>
          <td class="py-2 px-4 border-b border-gray-200"><%= inventory.item_type %></td>
          <td class="py-2 px-4 border-b border-gray-200"><%= inventory.price_per_piece %></td>
          <td class="py-2 px-4 border-b border-gray-200"><%= inventory.quantity %></td>
          <td class="py-2 px-4 border-b border-gray-200">
            <div class="flex space-x-2">
              <%= link_to 'Edit', edit_vendors_inventory_path(inventory), class: 'bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded' %>
              <%= button_to 'Delete', vendors_inventory_path(inventory), method: :delete, data: { confirm: 'Are you sure?' }, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2 class="text-2xl font-bold text-black mb-4">Orders</h2>
  <table class="min-w-full bg-white">
    <thead>
      <tr>
        <th class="py-2 px-4 bg-blue-500 text-white">Order ID</th>
        <th class="py-2 px-4 bg-blue-500 text-white">Customer</th>
        <th class="py-2 px-4 bg-blue-500 text-white">Total Price</th>
        <th class="py-2 px-4 bg-blue-500 text-white">Pizzas</th>
        <th class="py-2 px-4 bg-blue-500 text-white">Sides</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td class="py-2 px-4 border-b border-gray-200"><%= order.id %></td>
          <td class="py-2 px-4 border-b border-gray-200"><%= order.customer.name %></td>
          <td class="py-2 px-4 border-b border-gray-200"><%= order.total_price %></td>
          <td class="py-2 px-4 border-b border-gray-200">
            <% order.order_pizzas.each do |order_pizza| %>
              <p><%= order_pizza.pizza.name %> - <%= order_pizza.size %> - <%= order_pizza.crust %> - quantity: <%= order_pizza.quantity %> - price: <%= order_pizza.price %></p>
              <ul>
                <% order_pizza.order_pizza_toppings.each do |topping| %>
                  <li><%= topping.inventory.name %> - quantity: <%= topping.quantity %> - price: <%= topping.price %></li>
                <% end %>
              </ul>
            <% end %>
          </td>
          <td class="py-2 px-4 border-b border-gray-200">
            <% order.order_sides.each do |order_side| %>
              <p><%= order_side.inventory.name %> - <%= order_side.quantity %> - <%= order_side.price %></p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>