config/routes.rb
Rails.application.routes.draw do
  namespace :vendors do
    resources :pizzas, except: [ :index, :show ]
    resources :inventories, except: [ :index, :show ]
    get "home", to: "home#index", as: "home"
  end

  namespace :customers do
    resources :orders, only: [ :new, :create, :show ] do
      resources :order_sides, only: [ :new, :create ]
    end
    get "home", to: "home#index", as: "home"
  end

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  root "home#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  before_save :downcase_email

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/customers/home_controller.rb
class Customers::HomeController < ApplicationController
  before_action :require_user

  def index
    @pizzas = Pizza.includes(:pizza_sizes).all
    @toppings = Inventory.where(item_type: "topping")
    @sides = Inventory.where(item_type: "side")
  end
end

app/controllers/customers/order_sides_controller.rb
class Customers::OrderSidesController < ApplicationController
  before_action :require_user
  before_action :set_order

  def new
    @order_side = @order.order_sides.build
    @sides = Inventory.where(item_type: "side")
  end

  def create
    @order_side = @order.order_sides.build(order_side_params)
    if @order_side.save
      flash[:notice] = "Side added successfully."
      redirect_to customers_home_path
    else
      flash[:alert] = "Failed to add side."
      render :new
    end
  end

  private

  def set_order
    @order = Order.find(params[:order_id])
  end

  def order_side_params
    params.require(:order_side).permit(:inventory_id, :quantity, :price)
  end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  before_action :require_user
  before_action :setup_order_form, only: [ :new, :create ]

  def new
    @order = Order.new
    @order.order_pizzas.build
    @order.order_pizzas.first.order_pizza_toppings.build
    @order.order_sides.build
  end

  def create
    @order = OrderCreator.new(order_params).call
    if @order.id.present?
      redirect_to customers_order_path(@order), notice: "Order was successfully created."
    else
      render_with_flash("Failed to place order.")
    end
  end

  def show
    @order = Order
      .includes(:customer, order_pizzas: [ :pizza, :order_pizza_toppings ], order_sides: [ :inventory ])
      .find(params[:id])
  end

  private

  def render_with_flash(message)
    flash[:alert] = message
    render :new, alert: "Failed to place order."
  end

  def setup_order_form
    @customers = Customer.all
    @pizzas = Pizza.all
    @toppings = Inventory.where(item_type: "topping")
    @crusts = Inventory.where(item_type: "crust")
    @sides = Inventory.where(item_type: "side")
  end

  def order_params
    params.require(:order).permit(:customer_id, order_pizzas_attributes: [
      :pizza_id, :crust, :size, :quantity, :price, order_pizza_toppings_attributes: [
        :inventory_id, :quantity, :price
      ]
    ], order_sides_attributes: [ :inventory_id, :quantity ])
  end
end

app/controllers/customers/pizzas_controller.rb
class Customers::PizzasController < ApplicationController
  before_action :require_user

  def index
    @pizzas = Pizza.includes(:pizza_sizes).all
  end

  def show
    @pizza = Pizza.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
      if current_role == "vendor"
        redirect_to vendors_home_path
      else
        redirect_to customers_home_path
      end
    end
  end
end

app/controllers/vendors/home_controller.rb
class Vendors::HomeController < ApplicationController
  before_action :require_user
  before_action :require_vendor

  def index
    @orders = Order.includes(:customer, order_pizzas: [ :pizza, :order_pizza_toppings ], order_sides: [ :inventory ]).all
    @pizzas = Pizza.all
    @inventories = Inventory.all
  end
end

app/views/customers/home/index.html.erb
<div class="container mx-auto p-4">
  <h1 class="text-3xl font-bold text-black mb-4">Customer Dashboard</h1>
  <p class="text-lg text-black mb-4">Welcome, Customer!</p>

  <div class="flex items-center justify-between mb-4">
    <%= link_to "Place an Order", new_customers_order_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
  </div>

  <h1 class="text-3xl font-bold text-black mb-4">Menu</h1>

  <h2 class="text-2xl font-bold text-black mb-4">Pizzas</h2>
  <p class="text-md text-green-700 mb-4">With large size pizza, two toppings are free.</p>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    <% @pizzas.each do |pizza| %>
      <div class="bg-white p-4 rounded-lg shadow-lg">
        <h3 class="text-xl font-bold text-black mb-2"><%= pizza.name %></h3>
        <p class="text-sm mb-2 <%= pizza.is_vegetarian ? 'text-green-700' : 'text-red-700' %>">
          <%= pizza.is_vegetarian ? 'Vegetarian' : 'Non-Vegetarian' %>
        </p>
        <% pizza.pizza_sizes.each do |size| %>
          <p class="text-sm text-gray-700"><%= size.size.humanize %>: <span class="font-bold"><%= number_to_currency(size.price) %></span></p>
        <% end %>
      </div>
    <% end %>
  </div>

  <h2 class="text-2xl font-bold text-black mb-4 mt-8">Toppings</h2>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    <% @toppings.each do |topping| %>
      <div class="bg-white p-4 rounded-lg shadow-lg">
        <h3 class="text-xl font-bold text-black mb-2"><%= topping.name %></h3>

        <p class="text-sm text-gray-700">
          <span class="text-sm mb-2 <%= topping.category == 'veg' ? 'text-green-700' : 'text-red-700' %>">
            <%= topping.category&.humanize %>
          </span>
          -
          <span class="font-bold"><%= number_to_currency(topping.price_per_piece) %></span>
        </p>
      </div>
    <% end %>
  </div>

  <h2 class="text-2xl font-bold text-black mb-4 mt-8">Sides</h2>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    <% @sides.each do |side| %>
      <div class="bg-white p-4 rounded-lg shadow-lg">
        <h3 class="text-xl font-bold text-black mb-2"><%= side.name %></h3>
        <p class="text-sm text-gray-700">Price: <span class="font-bold"><%= number_to_currency(side.price_per_piece) %></span></p>
      </div>
    <% end %>
  </div>
</div>